on:
  push:
    branches:
      - main
    paths-ignore: [".github/**"]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run action
        id: hello-action 
        uses: ./hello-world-docker-action
        with:
          who-to-greet: "@LittleColin"
      - name: Output time set in the container
        run: echo "Hello-action ran at ${{ steps.hello-action.outputs.current-time }}"
          
        
      
